<?php
/**
 * Admin - Token Management
 */

// Check if user is logged in and is a super admin
if (!isset($_SESSION['user_id']) || $_SESSION['user_type'] !== 'admin' || $_SESSION['admin_level'] !== 'super') {
    header('Location: index.php?module=auth&action=login&type=admin');
    exit;
}

// Set page title and current page for navigation
$page_title = 'Admin Token Management';
$current_page = 'admin_tokens';

// Include header
require_once 'modules/admin/views/includes/header.php';
?>

<div class="container mt-4">
    <div class="row mb-4">
        <div class="col-md-8">
            <h2>Admin Token Management</h2>
            <p class="text-muted">Generate and manage admin registration tokens</p>
        </div>
        <div class="col-md-4 text-end">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#generateTokenModal">
                <i class="fas fa-plus"></i> Generate New Token
            </button>
        </div>
    </div>

    <!-- Token List -->
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Token</th>
                            <th>Admin Level</th>
                            <th>Generated By</th>
                            <th>Generated At</th>
                            <th>Expires At</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (isset($tokens) && !empty($tokens)): ?>
                            <?php foreach ($tokens as $token): ?>
                            <tr>
                                <td>
                                    <code><?php echo htmlspecialchars($token['token']); ?></code>
                                    <button class="btn btn-xs btn-link copy-token" 
                                            data-token="<?php echo htmlspecialchars($token['token']); ?>">
                                        <i class="fas fa-copy"></i>
                                    </button>
                                </td>
                                <td><?php echo ucfirst(htmlspecialchars($token['admin_level'])); ?></td>
                                <td><?php echo htmlspecialchars($token['generated_by_name']); ?></td>
                                <td><?php echo date('M d, Y H:i', strtotime($token['created_at'])); ?></td>
                                <td><?php echo date('M d, Y H:i', strtotime($token['expires_at'])); ?></td>
                                <td>
                                    <?php if (strtotime($token['expires_at']) < time()): ?>
                                        <span class="badge bg-danger">Expired</span>
                                    <?php elseif ($token['is_used']): ?>
                                        <span class="badge bg-success">Used</span>
                                    <?php else: ?>
                                        <span class="badge bg-primary">Active</span>
                                    <?php endif; ?>
                                </td>
                                <td class="action-buttons">
                                    <?php if (!$token['is_used'] && strtotime($token['expires_at']) > time()): ?>
                                        <button type="button" class="btn btn-xs btn-danger" 
                                                data-bs-toggle="modal" 
                                                data-bs-target="#revokeModal<?php echo $token['id']; ?>">
                                            <i class="fas fa-ban"></i> Revoke
                                        </button>

                                        <!-- Revoke Modal -->
                                        <div class="modal fade" id="revokeModal<?php echo $token['id']; ?>" tabindex="-1">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title">Revoke Token</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Are you sure you want to revoke this token? This action cannot be undone.</p>
                                                        <code><?php echo htmlspecialchars($token['token']); ?></code>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                                        <a href="index.php?module=admin&action=revoke_token&id=<?php echo $token['id']; ?>" 
                                                           class="btn btn-danger">Revoke Token</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="7" class="text-center">No tokens found</td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Generate Token Modal -->
<div class="modal fade" id="generateTokenModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Generate New Admin Token</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form action="index.php?module=admin&action=generate_token" method="POST">
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="admin_level" class="form-label">Admin Level</label>
                        <select class="form-select" id="admin_level" name="admin_level" required>
                            <option value="">Choose...</option>
                            <option value="standard">Standard Admin</option>
                            <option value="super">Super Admin</option>
                        </select>
                        <div class="form-text">Super admins can generate new tokens and manage other admins.</div>
                    </div>
                    <div class="mb-3">
                        <label for="expiry_hours" class="form-label">Token Validity (hours)</label>
                        <input type="number" class="form-control" id="expiry_hours" name="expiry_hours" 
                               value="24" min="1" max="168" required>
                        <div class="form-text">Token will expire after specified hours (max 7 days).</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Generate Token</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
// Copy token functionality
document.addEventListener('DOMContentLoaded', function() {
    const copyButtons = document.querySelectorAll('.copy-token');
    copyButtons.forEach(button => {
        button.addEventListener('click', function() {
            const token = this.dataset.token;
            navigator.clipboard.writeText(token).then(() => {
                // Show temporary success message
                const icon = this.querySelector('i');
                icon.classList.remove('fa-copy');
                icon.classList.add('fa-check');
                setTimeout(() => {
                    icon.classList.remove('fa-check');
                    icon.classList.add('fa-copy');
                }, 2000);
            });
        });
    });
});
</script>

<?php
// Include footer
require_once 'modules/admin/views/includes/footer.php';
?> 